# Run these tests if tests were changed.
name: Run Tests By Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**.Tests/**'
  pull_request:
    branches: [ main ]

jobs:
  Build-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Replace tokens # replace tokens in appsettings.json with real data
      uses: cschleiden/replace-tokens@v1.1
      with:
        files: '["**/*.json"]'
      env:
          ServiceUrl: ${{secrets.SERVICEURL}}
          NAME: ${{secrets.NAME}}
          PrivateKey: ${{secrets.PRIVATEKEY}}
          PublicBody: ${{secrets.PUBLICBODY}}
          AlfaAlias: ${{secrets.ALFAALIAS}}

    - name: Test with the dotnet CLI
      run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx"

    - name: Tests report
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Test results
        path: '**/test-results.trx'
        reporter: dotnet-trx
